<div class="container">
	<div class="prepend-6 span-9">
	<a href="<?php echo $this->url(
		array(
			'controller'=>'monitory',
	       	        'action'    =>'index'
		),
		'default',
		true) ?>">Strona Edycji</a>
	</div>
	<div class="span-9 last">
	<a href="<?php echo $this->url(
		array(
			'controller'=>'index',
	       	        'action'    =>'index'
		),
		'default',
		true) ?>">Strona glowna</a>
	</div>

	<div class="prepend-8 span-12 prepend-top">
		<h3><?php echo $this->error;?></h3>
        <?php $this->form->setAction($this->url());
        $this->form->Cale;
		echo $this->form;?>
	</div>
</div>
