<div class="container">
	<div class="prepend-6 span-9">
	<a href="<?php echo $this->url(
		array(
			'controller'=>'searches',
	       	        'action'    =>'index'
		),
		'default',
		true) ?>">Strona porownywania</a>
	</div>
	<div class="span-9 last">
	<a href="<?php echo $this->url(
		array(
			'controller'=>'index',
	       	        'action'    =>'index'
		),
		'default',
		true) ?>">Strona glowna</a>
	</div>

	<div class="prepend-2 span-6 prepend-top">
	<a href="<?php echo $this->url(
		array(
			'controller'=>'monitory',
	       	        'action'    =>'add'
		),
		'default',
		true) ?>">Dodaj Przedmiot</a>
	</div>
	<div class="span-6 prepend-top">
	<a href="<?php echo $this->url(
		array(
			'controller'=>'monitory',
	       	        'action'    =>'addByParsing'
		),
		'default',
		true) ?>">Dodaj Przedmiot po nazwie</a>
	</div>
	<div class="span-6 prepend-top">
	<a href="<?php echo $this->url(
		array(
			'controller'=>'monitory',
			'action'    =>'edit'
		),
		'default',
		true) ?>">Edytuj Przedmioty</a>
	</div>
	<div class="span-4 prepend-top last">
	<a href="<?php echo $this->url(
		array(
			'controller'=>'monitory',
			'action'    =>'delete'
		),
		'default',
		true) ?>">Usun Przedmioty</a>
	</div>
</div>
