<div class="container">
	<div class="span-12">
	<a href="<?php echo $this->url(
		array(
			'controller'=>'narzedzia',
	       	        'action'    =>'index'
		),
		'default',
		true) ?>">Dodaj/Edytuj/Usun Przedmioty</a>
	</div>
	<div class="span-12 last">
	<a href="<?php echo $this->url(
		array(
			'controller'=>'wyszukiwarka',
			'action'    =>'index'
		),
		'default',
		true) ?>">Wyszukaj Przedmioty</a>
	</div>
</div>
