<div class="container">
	<div class="prepend-6 span-8">
	<a href="<?php echo $this->url(
		array(
			'controller'=>'index',
			'action'    =>'index'
		),
		'default',
		true) ?>">Strona główna</a>
	</div>
	<div class="span-8 last">
	<a href="<?php echo $this->url(
		array(
			'controller'=>'searches',
			'action'    =>'index'
		),
		'default',
		true) ?>">Strona kupującego</a>
	</div>
<?php if ($this->categories) { ?>
    <div class="prepend-1 span-9 prepend-top last">
        <form id="selectCategory" method="POST">
	        <label for="category">Wybierz kategorię oferowanych przedmiotów:</label><br>
	        <select id="category" name="category">
                <option value="<?= $this->actualCategory; ?>"><?= $this->actualCategory; ?></option>
		        <?php foreach ($this->categories as $category): ?>
                    <?php if ($category['name'] != $this->actualCategory) { ?>
        		        <option value="<?= $category['name']; ?>"><?= $category['name'] ?></option>
                    <? } ?>
		        <?php endforeach;?>
	        </select>
	        <input type="submit" value="wybierz" />  	
        </form>
    </div>
<? } ?>
<div class="prepend-top span-24 last">
<? if ($this->allOffers) { ?>
    <table id='tableOffers'>
        <tr>
            <th>Kategoria</th>       
		    <th>Producent</th>
		    <th>Nazwa</th>
		    <th>Cena</th>
		    <th>Promocja</th>
		    <th>Opis</th>
		    <th>Magazyn</th>
		    <th>Cena hurtowa</th>
		    <th>Raty</th>
		    <th>Opcje</th>
	    </tr> 
            <?= $this->partialLoop("partials/offer.phtml", $this->allOffers); ?>
    </table>
<? } ?>
</div>
