<div class="container">
	<div class="prepend-6 span-8">
	<a href="<?php echo $this->url(
		array(
			'controller'=>'index',
			'action'    =>'index'
		),
		'default',
		true) ?>">Strona główna</a>
	</div>
	<div class="span-8 last">
	<a href="<?php echo $this->url(
		array(
			'controller'=>'searches',
			'action'    =>'index'
		),
		'default',
		true) ?>">Strona kupującego</a>
	</div>
<?php if ($this->categories) { ?>
    <form id="frm" method="POST">
	    <label for="name">name:</label>
	    <input type="text" name="name" id="name" value="<?= $this->name; ?>" /> 

	    <label for="email">email:</label>
	    <input type="text" name="email" id="email" value="<?= $this->email; ?>" /> 

	    <label for="contactType">contact type:</label>
	    <select id="contactType" name="contactType" >
		    <option value=""> -- </option>		
		    <?php foreach ($this->contactTypes as $type): ?>
		    <option value="<?= $type->id; ?>" 
			    <?= ($type->id == $this->contacttype_id) ? 'SELECTED="1"' : ''  ?> >
		    <?= $type->name; ?></option>
		    <?php endforeach;?>
	    </select>
	    <input type="submit" name="btsubmit" id="btsubmit" value="submit" />  	
    </form>
<? } ?>
