<div class="span-17">
    <fieldset>
    <div class="span-1">
        <input type="checkbox" value="<?= $this->nazwa ?>" name="<?= $this->nazwa ?>">  
    </div>
	<div class="span-5"><h4>Producent: <strong><? echo $this->marka; ?></strong></h4><br>
                        <h4>Nazwa: <strong><? echo $this->nazwa; ?></strong></h4>
    </div>
    <div class="span-6">
	    <table id="tableOffers">
	    	<tr>
	    		<th>Parametr:</th>
				<th>Wartość:</th>
			</tr>
	    	<tr>
	    		<td>Pojemność:</td>
				<td><?php echo $this->pojemnosc;?></td>
			</tr>
	    	<tr>
	    		<td>Prędkość:</td>
				<td><?php echo $this->predkosc;?></td>
			</tr>
	    	<tr>
	    		<td>Złącze:</td>
				<td><?php echo $this->zlacze;?></td>
			</tr>
		</table>
    </div>    
    <div class="span-4 last">
            <img src="http://www.samsung.com/pl/system/consumer/product/2009/07/29/hxsu016ba/02_medium.jpg" width="100" hight="100" align="right">
    </div>
    </fieldset>
</div>
