<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
   "http://www.w3.org/TR/xhtml1/DTD/ xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<script type="text/javascript">
var chmurka, IE=document.all?true:false;

if(!IE) { 
document.captureEvents(Event.MOUSEMOVE);
document.onmousemove=mousePos;
var netX, netY; 
}

function init(){
if(IE) chmurka=document.all.chmurka; 
else chmurka=document.getElementById("chmurka");
b=document.body;
}
function mousePos(e) {
netX=e.pageX;netY=e.pageY;
}
function chmurka_Move(ix, iy) {
init();
if(chmurka.style.visibility!='visible') return;
if(IE) {
msx=event.clientX; 
msy=event.clientY;
} 
else {
msx=netX-b.scrollLeft; 
msy=netY-b.scrollTop;
}
temix=msx+ix;
if(temix<0) temix=0;
tmp=b.clientWidth-msx-ix-chmurka.offsetWidth-20;
if(tmp<0) {
temix+=tmp; 
if(temix<0) temix=0;
}
chmurka.style.left=b.scrollLeft+temix+"px";
temiy=msy+iy;
if(temiy<0) temiy=0;
tmp=b.clientHeight-msy-iy-chmurka.offsetHeight-15;
if(tmp<0) {
tmp=msy-15-chmurka.offsetHeight;
if(tmp>=0) temiy=tmp;
  }
chmurka.style.top=b.scrollTop+temiy+"px";
}
function chmurkaShow(ix, iy, src){ 
init(); 
chmurka.style.visibility='visible'; 
chmurka.innerHTML=src; chmurkaMove(ix,iy); 
}
function chmurkaClose() {
init();
chmurka.style.visibility='hidden';
chmurka.innerHTML=''; 
chmurka.style.left=0;
chmurka.style.top=0;
}
function chmurkaMsg(tmsg) {
text='<table cellspacing="0" cellpadding="6" style="border: solid 1px #008206; background:#E9FFEB; font-family: Verdana,sans-serif; font-size:10px;" ><tr><td style="text-align:left; color:black;">'+tmsg+'</td></tr></table>'; 
chmurkaShow(10,20,text);
}
function chmurkaMove() {
chmurka_Move(10,10);
}
</script>

</head>
<div class="container">
	<div class="prepend-6 span-8">
	<a href="<?php echo $this->url(
		array(
			'controller'=>'index',
			'action'    =>'index'
		),
		'default',
		true) ?>">Strona główna</a>
	</div>
	<div class="span-8 last">
	<a href="<?php echo $this->url(
		array(
			'controller'=>'client',
			'action'    =>'index'
		),
		'default',
		true) ?>">Strona kupującego</a>
	</div>
<?php if ($this->errorMessage) { ?>
    <div class="prepend-5 span-14 append-5 prepend-top">
        <h3><?= $this->errorMessage ?></h3>
    </div>
<? } ?>

<?php if ($this->categories) { ?>
	<div class="span-5 prepend-top last">
		<table id="tableCategories">
			<tr>
				 <th>KATEGORIE</th>
			</tr>
			<?php foreach($this->categories as $category) : ?>
			<tr>
				<td>
                    <a href="<?php echo $this->url(array('controller'=>'client', 'action'=>'search', 'category'=>$category->name));?>"><?php echo $category->name;?></a>
                </td>
			</tr>
    		<?php endforeach; ?>
		</table>
    </div>
<? } ?>
<?php if ($this->fieldsNamesArray) { ?>
    <div id="chmurka" style="position: absolute; visibility: hidden;z-index:2;"></div>
	    <div class="prepend-1 span-17 append-1 prepend-top">
            <form id="searchForm" method="POST">
                <fieldset id="searchField"><legend><?= $this->category; ?><input type="submit" value="szukaj" /></legend>
                    <?php $i=0;
                        while(isset($this->fieldsNamesArray[$i])) { ?>
                        <div class="span-3">
                            <fieldset id="fieldset1"><legend align="left"><?= $this->fieldsNamesArray[$i] ?><img onmouseover="chmurkaMsg('<?php echo $this->fieldsDescriptions[$this->fieldsNamesArray[$i]] ?>');" onmousemove="chmurkaMove();" onmouseout="chmurkaClose(); "src="http://www.profinfo.pl/home/401/des/_gfx/znakZapytania.png" width="22" hight="22"></legend>
                            <?php $y=0;
                                foreach ($this->tableWithAllValueEveryFields[$this->fieldsNamesArray[$i]] as $value) { ?>
                                <input type="checkbox" name="<?= $this->fieldsNamesArray[$i]?><?=$y?>" value="<?= $value[$this->fieldsNamesArray[$i]] ?>"><? $y++ ?>
                            	<label "><?= $value[$this->fieldsNamesArray[$i]] ?></label><br>
                            <? } ?>
                            </fieldset>
                        </div>          
                    <?$i++;
                    } ?>
                    
                 </fieldset>
            </form>
            
    <? if ($this->items) { ?>
        <form id="searchForm" method="POST">
            <input type="submit" value="porownaj" />
            <input type="hidden" value="compare" name="compare">
            <?= $this->partialLoop("partials/client/$this->category.phtml", $this->items); ?>
        </form>
    <? } ?>
        </div>
    <? } ?>
    
</div>
