<div class="container">
	<div class="span-8">
	<a href="<?php echo $this->url(
		array(
			'controller'=>'searches',
	       	        'action'    =>'search'
		),
		'default',
		true) ?>">Znajdz Przedmiot</a>
	</div>
	<div class="span-8">
	<a href="<?php echo $this->url(
		array(
			'controller'=>'monitors',
	       	        'action'    =>'add'
		),
		'default',
		true) ?>">Dodaj nowy przedmiot</a>
	</div>
	<div class="span-8 last">
	<a href="<?php echo $this->url(
		array(
			'controller'=>'index',
	       	        'action'    =>'index'
		),
		'default',
		true) ?>">Strona glowna</a>
	</div>

<? if ($this->monitor) {?>
	<div class="append-3 span-18 prepend-3 prepend-top">	
		<table>
			<tr>
				<div class="span-6"><th><h3>Producent:</h3></th></div>
				<div class="span-6"><td><h3><strong><? echo $this->monitor[marka]; ?></strong></h3></td></div>
				<div class="span-6 last"><td><h3><strong><? echo $this->monitor2[marka]; ?></strong></h3></td></div>
			</tr>
			<tr>	
				<div class="span-6"><th><h3>Nazwa:</h3></th></div>
				<div class="span-6"><td><h3><strong><? echo $this->monitor[nazwa]; ?></strong></h3></td></div>
				<div class="span-6 last"><td><h3><strong><? echo $this->monitor2[nazwa]; ?></strong></td></h3></div>
			</tr>
			<tr>
				<div class="span-6"><th>Jasnosc(cd/m2):</th></div>
				<div class="span-6"><td><?php echo $this->monitor[Jasnosc];?></td></div>
				<div class="span-6 last"><td><?php echo $this->monitor2[Jasnosc];?></td></div>
			</tr>
			<tr>
				<div class="span-6"><th>Cale:</th></div>
				<div class="span-6"><td><?php echo $this->monitor[Cale];?></td></div>
				<div class="span-6 last"><td><?php echo $this->monitor2[Cale];?></td></div>
			</tr>
			<tr>
				<div class="span-6"><th>Reakcja matrycy(ms):</th></div>
				<div class="span-6"><td><?php echo $this->monitor[Reakcja];?></td></div>
				<div class="span-6 last"><td><?php echo $this->monitor2[Reakcja];?></td></div>
			</tr>
			<? if ($this->cena) {?>
			<tr>
				<div class="span-6"><th>Cena od(zł):</th></div>
				<div class="span-6"><td><?php echo $this->cena;?></td></div>
				<div class="span-6 last"><td><?php echo $this->cena2;?></td></div>
			<? } ?>
		</table>
	</div>
<? } ?>
	<div class="prepend-3 span-21 prepend-top last">
		<table>
			<tr>
				 <th>Producent</th>
				 <th>Nazwa</th>
				 <th>Opcje</th>
			</tr>
			<?php foreach($this->monitory as $monitor) : ?>
			<tr>
				<td><?php echo $this->escape($monitor->marka);?></td>
				<td><?php echo $this->escape($monitor->nazwa);?></td>
				<td>
				<a href="<?php echo $this->url(array('controller'=>'searches',
					      'action'=>'index', 'id'=>$monitor->id));?>">Wyswietl</a>	
				<a href="<?php echo $this->url(array('controller'=>'monitors',
					      'action'=>'edit', 'id'=>$monitor->id));?>">Edit</a>
					<a href="<?php echo $this->url(array('controller'=>'monitors',
					      'action'=>'delete', 'id'=>$monitor->id));?>">Delete</a>
					<a href="<?php echo $this->url(array('controller'=>'searches',
					      'action'=>'index', 'id2'=>$monitor->id));?>">Dodaj do porownywanych</a>
				</td>
			</tr>
		<?php endforeach; ?>
		</table>
	</div>
</div>
