<div class="container">
	<div class="span-12">
	<a href="<?php echo $this->url(
		array(
			'controller'=>'searches',
	       	        'action'    =>'index'
		),
		'default',
		true) ?>">Strona Porownywania</a>
	</div>
	<div class="span-12 last">
	<a href="<?php echo $this->url(
		array(
			'controller'=>'index',
	       	        'action'    =>'index'
		),
		'default',
		true) ?>">Strona glowna</a>
	</div>

	<div class="span-6 prepend-top last">
		<?php
		$this->form->setAction($this->url());
		echo $this->form;
		?>
	</div>
	<div class="span-18 prepend-top">	
	<? if ($this->monitor) {?>
			<div class="span-9"><h3>Producent:</h3></div><div class="span-9 last"><h3><strong><? echo $this->monitor[marka]; ?></strong></h3></div>
			<div class="span-9"><h3>Nazwa:</h3></div><div class="span-9 last"><h3><strong><? echo $this->monitor[nazwa]; ?></strong></h3></div>
		</div>
		<div class="span-18 last">
			<table>
				<tr>
					<td>Jasnosc:</td>
					<td><?php echo $this->monitor[Jasnosc];?></td>
				</tr>
				<tr>
					<td>Cale:</td>
					<td><?php echo $this->monitor[Cale];?></td>
				</tr>
				<tr>
					<td>Reakcja matrycy:</td>
					<td><?php echo $this->monitor[Reakcja];?></td>
				</tr>
				<tr>
					<td>Kontrast:</td>
					<td><?php echo $this->monitor[Kontrast];?></td>
				</tr>
				<tr>
					<td>Rozdzielczosc:</td>
					<td><?php echo $this->monitor[Rozdzielczosc];?></td>
				</tr>
				<tr>
					<td>Katy (poziomo/pionowo):</td>
					<td><?php echo $this->monitor[Katy];?></td>
				</tr>
				<tr>
					<td>Kolor:</td>
					<td><?php echo $this->monitor[Kolor];?></td>
				</tr>
				<tr>
					<td>Pobór mocy(włączony):</td>
					<td><?php echo $this->monitor[Pobor];?></td>
				</tr>
				<tr>
					<td>Pobór mocy(czuwanie):</td>
					<td><?php echo $this->monitor[Czuwanie];?></td>
				</tr>
				<tr>
					<td>Waga(w kilogramy):</td>
					<td><?php echo $this->monitor[Waga];?></td>
				</tr>
			</table>
		</div>
	</div>
<? } ?>
</div>
