<div class="container">
	<div class="span-6 prepend-top last">
		<?php
		$this->form->setAction($this->url());
		echo $this->form;
		?>
	</div>
	<div class="span-18 prepend-top">	
	<? if ($this->monitor) {?>
			<div class="span-9"><h3>Producent:</h3></div><div class="span-9 last"><h3><strong><? echo $this->monitor[marka]; ?></strong></h3></div>
			<div class="span-9"><h3>Nazwa:</h3></div><div class="span-9 last"><h3><strong><? echo $this->monitor[nazwa]; ?></strong></h3></div>
		</div>
		<div class="span-18 last">
			<table>
				<tr>
					<td>Jasnosc:</td>
					<td><?php echo $this->monitor[Jasnosc];?></td>
				</tr>
				<tr>
					<td>Cale:</td>
					<td><?php echo $this->monitor[Cale];?></td>
				</tr>
				<tr>
					<td>Reakcja matrycy:</td>
					<td><?php echo $this->monitor[Reakcja];?></td>
				</tr>
			</table>
		</div>
	</div>
<? } ?>
</div>
