<div class="span-6 prepend-top">
	<div class="span-3"><h3>Producent:</h3></div><div class="span-3 last"><h3><strong><? echo $this->marka; ?></strong></h3></div>
	<div class="span-3"><h3>Nazwa:</h3></div><div class="span-3 last"><h3><strong><? echo $this->nazwa; ?></strong></h3></div>
</div>
<div class="span-6 last">
			<table>
				<tr>
					<td>Pojemnosc:</td>
					<td><?php echo $this->pojemnosc;?></td>
				</tr>
			</table>
</div>
