<div class="span-6 prepend-top last">
	<div class="span-3"><h3>Producent:</h3></div><div class="span-3 last"><h3><strong><? echo $this->marka; ?></strong></h3></div>
	<div class="span-3"><h3>Nazwa:</h3></div><div class="span-3 last"><h3><strong><? echo $this->nazwa; ?></strong></h3></div>
			<table>
				<tr>
					<td>Jasnosc:</td>
					<td><?php echo $this->Jasnosc;?></td>
				</tr>
				<tr>
					<td>Cale:</td>
					<td><?php echo $this->Cale;?></td>
				</tr>
				<tr>
					<td>Reakcja matrycy:</td>
					<td><?php echo $this->Reakcja;?></td>
				</tr>
				<tr>
					<td>Kontrast:</td>
					<td><?php echo $this->Kontrast;?></td>
				</tr>
				<tr>
					<td>Rozdzielczosc:</td>
					<td><?php echo $this->Rozdzielczosc;?></td>
				</tr>
				<tr>
					<td>Katy (poziomo/pionowo):</td>
					<td><?php echo $this->Katy;?></td>
				</tr>
				<tr>
					<td>Kolor:</td>
					<td><?php echo $this->Kolor;?></td>
				</tr>
				<tr>
					<td>Pobór mocy(włączony):</td>
					<td><?php echo $this->Pobor;?></td>
				</tr>
				<tr>
					<td>Pobór mocy(czuwanie):</td>
					<td><?php echo $this->Czuwanie;?></td>
				</tr>
				<tr>
					<td>Waga(w kilogramy):</td>
					<td><?php echo $this->Waga;?></td>
				</tr>
			</table>
</div>
